version: "3.8"

services:
  angular:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "${ANGULAR_PORT}:80"
    depends_on:
      - laravel
    networks:
      - mainTunnel

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - database
    networks:
      - mainTunnel
      - databaseNetwork
    restart: always

  database:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - databaseNetwork
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: "${DB_PORT}"
    ports:
      - "${PHP_MY_ADMIN_PORT}:80"
    depends_on:
      - database
    networks:
      - databaseNetwork
    restart: always

networks:
  mainTunnel:
    driver: bridge
  databaseNetwork:
    driver: bridge
volumes:
  db_data:
